### ISSUE TITLE
能否增加 RSS？

### ISSUE THREAD

**Issue by sbilly** [ying-zhang/ying-zhang.github.io#1]
能否增加 RSS ？方便订阅哈。

**Comment by sbilly** [comment]
找到了

**Comment by ying-zhang** [comment]
多谢关注！
RSS链接是https://ying-zhang.github.io/atom.xml。
惭愧好久没有写东西了。
考虑到很多RSS客户端已经停止服务了，所以考虑开个微信公众号；
此外感觉hexo主题的排版还是有点小问题，但手写html又比较繁琐，考虑要不要学习一点前端技能。
